blank_issues_enabled: false
contact_links:
  - name: ✏️ FAQ
    url: https://github.com/SrGobi/SpotX/discussions
    about: Read the frequently asked questions, maybe it will help solve your problem right now.
